# config.yaml
directory_path: "/Users/joesasson/Desktop/articles/rag-from-scratch/text_data"
embedding_model: "BAAI/bge-small-en-v1.5"
chunk_size: 256
document_types: ["txt", "pdf", "md"]
llm_model: "mistral-7b-instruct-v0.2.Q4_K_M.gguf"